### ISSUE TITLE
Loop infinito

### ISSUE THREAD

**Issue by developerspro** [Rynnila/Atividade_Paciente_DES#1]
https://github.com/Rynnila/Atividade_Paciente_DES/blob/ca06187c0795d6ffda993fcb45ac7ee8ff834bd9/AtvHospitalDES/Program.cs#L36

while esta em looping, pois a variável i não está sendo alterada

**Comment by Rynnila** [comment]
while (j < 3)
                    {
                        Console.WriteLine(pac[j].nome);
                        j++;
                    }
