### ISSUE TITLE
Concatenação entre linhas

### ISSUE THREAD

**Issue by MikaelMedeirosx** [Rynnila/Atividade_Paciente_DES#4]
Para pular linhas em C# é só colocar "\n" entre os  parênteses no começo ou no final do Console.WriteLine, por exemplo:

Console.WriteLine("\nInsira as seguintes informações do paciente: ");

https://github.com/Rynnila/Atividade_Paciente_DES/blob/ca06187c0795d6ffda993fcb45ac7ee8ff834bd9/AtvHospitalDES/Paciente.cs#L50

**Comment by Rynnila** [comment]
Obrigada <3 
Erro consertado
